spring:
  datasource:
    username: root
    password: lin2487049041
    url: jdbc:mysql://127.0.0.1:3306/francis_blog?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 127.0.0.1
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 8080
  servlet:
    context-path: /francisblog/api/v1
logging:
  config: classpath:log/logback-spring.xml
  file:
    path: /root/mcms/log
